plugins:
  - jekyll-relative-links
  - jekyll-sitemap

remote_theme: chrisrhymes/bulma-clean-theme@v0.12

title: "A new approach to achieve quality"
description: Qualitic Maturity Model is a new approach to measure, guide, and empower the quality of the product development team, with respect to a set of clear rules.
footer_menu: footer
defaults:
  - scope:
      path: ""
    values:
      menubar_toc: true
      hero_image: https://media.githubusercontent.com/media/qualiticcommunity/qualiticcommunity.github.io/master/assets/img/hero-background.webp
      title: Qualitic Maturity Model
