plugins:
  - jekyll-relative-links
  - jekyll-sitemap

remote_theme: chrisrhymes/bulma-clean-theme@72f7a305a1914c583bdcb9968d0051aa980b7aa0

title: ""
defaults:
  -
    scope:
          path: ""
    values:    
      menubar_toc: true
