plugins:
  - jekyll-relative-links
  - jekyll-sitemap

remote_theme: chrisrhymes/bulma-clean-theme@v.0.12

title: "A new approach to measure, guide, and empower the dev team."
defaults:
  -
    scope:
          path: ""
    values:    
      menubar_toc: true
