plugins:
  - jekyll-relative-links
  - jekyll-sitemap

remote_theme: chrisrhymes/bulma-clean-theme@v.0.12

title: ""
defaults:
  -
    scope:
          path: ""
    values:    
      menubar_toc: true
