name: Spellcheck
on:
  pull_request:
    branches:
      - master
jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@0.29.0
        with:
          config_path: .spellcheck/config.yml
